- name: Update osp-app
  hosts: all
  vars:
  - osp_app_directory: /home/mako/osp-app
  - out_of_date: no
  - enough_space: no
  - app_space_multiplier: 2.5
  - space_needed: 0
  - available_space: 0
  - ruby_compatible: no
  - rocketchat_message: ./rocketchat_message
  tasks:
    - name: Init Rocket.Chat
      block:
        - include: rocketchat_initialize.yml

    - name: Update osp-app - Main
      block:
        - include: osp-app_update.yml
      rescue:
        - name: Catch error 
          lineinfile:
            path: "{{ rocketchat_message }}"
            line: ":x: _{{ ansible_failed_task['name'] }}_ failed"
      always:
        - include: rocketchat_finalize.yml
